// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY8Nti8mRjURY3CvAkNfbP1X1oWFZc1VI',
    appId: '1:665931155981:web:e28da039051705c34be344',
    messagingSenderId: '665931155981',
    projectId: 'fcm-sample-2709',
    authDomain: 'fcm-sample-2709.firebaseapp.com',
    storageBucket: 'fcm-sample-2709.appspot.com',
    measurementId: 'G-H09YK0K9XX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-QpBw_BVMcltTGIo1DgSZwN-xF0YH0Y0',
    appId: '1:665931155981:android:8fcb5197141500cd4be344',
    messagingSenderId: '665931155981',
    projectId: 'fcm-sample-2709',
    storageBucket: 'fcm-sample-2709.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4NmEga42lje7F0KF-aMEz-4VfxvjR5no',
    appId: '1:665931155981:ios:22b9546fd2fff64a4be344',
    messagingSenderId: '665931155981',
    projectId: 'fcm-sample-2709',
    storageBucket: 'fcm-sample-2709.appspot.com',
    iosBundleId: 'com.example.fcmSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4NmEga42lje7F0KF-aMEz-4VfxvjR5no',
    appId: '1:665931155981:ios:22b9546fd2fff64a4be344',
    messagingSenderId: '665931155981',
    projectId: 'fcm-sample-2709',
    storageBucket: 'fcm-sample-2709.appspot.com',
    iosBundleId: 'com.example.fcmSample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY8Nti8mRjURY3CvAkNfbP1X1oWFZc1VI',
    appId: '1:665931155981:web:56ad9f57b596782d4be344',
    messagingSenderId: '665931155981',
    projectId: 'fcm-sample-2709',
    authDomain: 'fcm-sample-2709.firebaseapp.com',
    storageBucket: 'fcm-sample-2709.appspot.com',
    measurementId: 'G-7CJGFY9P0P',
  );
}
